import type { ResultViewModel } from "../shared/types";

export function createResultViewModel(overrides: Partial<ResultViewModel> = {}): ResultViewModel {
  return {
    summary: {
      request_id: "req-1",
      user_input: "Qingdao",
      plan_intent: "weather_and_fashion",
      plan_location: "Qingdao",
      selected_city: "Qingdao, Shandong, China",
      resolution_status: "resolved",
      resolution_confidence: 0.88,
      message: "Query complete",
      error: "",
      used_fast_path: true,
      graph_runtime: "langgraph",
      total_elapsed_ms: 1200,
      requested_at: "",
      completed_at: "",
      models_used: [],
      confirmation_mode: "smart",
      location_source: "text_search",
      location_source_label: "Text search",
      selected_coords: undefined,
      timezone_label: "UTC+08:00",
      confirmed_location_label: "Qingdao, Shandong, China",
      locale: "zh-CN",
      query_context: {
        gender: "neutral",
        occasion_text: "上班通勤，办公室有空调",
        occasion_tags: ["work", "air_conditioning"],
        target_date: "2026-03-24",
        forecast_mode: "current",
      },
    },
    hero_summary: {
      title: "Qingdao, Shandong, China",
      condition: "多云",
      condition_emoji: "🌤️",
      temperature: "8.9°C",
      feels_like: "6.1°C",
      daily_range_text: "7.5°C ~ 9.0°C",
      advice_label: "今日建议",
      one_line_advice: "全天偏凉，建议保暖内搭配轻外套，出门记得考虑风感。",
      status_message: "查询完成",
      query_path: "快速路径",
    },
    weather: {
      ok: true,
      city: "Qingdao, Shandong, China",
      coords: "36.0671, 120.3826",
      temperature: "8.9°C",
      feels_like: "6.1°C",
      temp_min: "7.5°C",
      temp_max: "9.0°C",
      daily_range_text: "7.5°C ~ 9.0°C",
      description: "多云",
      humidity: "75%",
      wind: "5.2 m/s",
      source: "openweather_latlon",
      data_mode: "real_latlon",
      observed_at: "2026-03-24T12:00:00+00:00",
      observed_at_local: "2026-03-24 20:00",
      city_local_time: "2026-03-24 20:05",
      timezone_label: "UTC+08:00",
      request_elapsed_ms: 340,
      error: "",
      forecast_date: "2026-03-24",
      forecast_mode: "current",
    },
    weather_metrics: [
      {
        key: "temperature_overview",
        label: "温度概览",
        value: "8.9°C",
        icon: "🌤️",
        tone: "primary",
        subvalue_left: "7.5°C",
        subvalue_right: "9.0°C",
      },
      { key: "feels_like", label: "体感温度", value: "6.1°C", icon: "🫠", tone: "info" },
      { key: "humidity", label: "湿度", value: "75%", icon: "💧", tone: "info" },
      { key: "wind", label: "风速", value: "5.2 m/s", icon: "🌬️", tone: "info" },
    ],
    fashion: {
      text: "",
      headline_advice: "全天偏凉，建议保暖内搭配轻外套，出门记得考虑风感。",
      time_of_day_advice: "- 早晨：加一层防风外套。\n- 白天：可减掉中层。",
      layering_advice: "- 内层：长袖打底。\n- 中层：薄针织。\n- 外层：轻外套。",
      bottomwear_advice: "- 下装：长裤更稳妥，若穿裙装建议配打底。",
      shoes_accessories_advice: "- 鞋子：闭口运动鞋。\n- 配饰：轻围巾。",
      notes_advice: "- 通勤场景下，进办公室后记得保留一层可脱外搭。",
      source: "rule_based_fashion",
      used_llm: false,
      error: "",
    },
    fashion_sections: [
      { key: "time_of_day", title: "分时段建议", content: "- 早晨：加一层防风外套。\n- 白天：可减掉中层。" },
      { key: "layering", title: "上装分层", content: "- 内层：长袖打底。\n- 中层：薄针织。\n- 外层：轻外套。" },
      { key: "bottoms", title: "下装建议", content: "- 下装：长裤更稳妥，若穿裙装建议配打底。" },
      { key: "shoes_accessories", title: "鞋子与配饰", content: "- 鞋子：闭口运动鞋。\n- 配饰：轻围巾。" },
      { key: "notes", title: "结果补充", content: "- 通勤场景下，进办公室后记得保留一层可脱外搭。" },
    ],
    knowledge_basis: {
      status: "matched",
      summary: "已命中与当前天气和场景相关的知识依据。",
      items: [
        {
          id: "wide-range-layer",
          label: "昼夜温差大时准备可脱卸外层",
          short_reason: "温差较大，建议保留一层可增减的外层。",
        },
      ],
    },
    decision_factors: ["体感偏低，建议优先按体感穿衣。", "风速较明显，外层需要更防风。"],
    explanation_reasons: ["体感偏低，建议优先按体感穿衣。"],
    bottomwear_section: {
      title: "下装建议",
      content: "- 下装：长裤更稳妥，若穿裙装建议配打底。",
    },
    location_pin: {
      lat: 36.0671,
      lon: 120.3826,
      label: "Qingdao, Shandong, China",
      source: "geocoding",
      confirmed: true,
      zoom_hint: 8,
    },
    clarification: {
      needed: false,
      message: "",
      recommended_candidate_id: "",
      current_selection_label: "Qingdao, Shandong, China",
      options: [],
    },
    clarification_panel: {},
    timeline_steps: [],
    trace: [],
    warnings: [],
    badges: [
      { key: "weather_mode", label: "天气模式", value: "real_latlon" },
      { key: "confirmation_mode", label: "确认模式", value: "智能模式" },
    ],
    recent_queries: [],
    dependency_status: {},
    metrics_snapshot: {},
    debug_sections: {
      knowledge: [],
    },
    ...overrides,
  };
}
